import { useState } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import { useQuery } from "@tanstack/react-query";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { ExternalLink, Loader2, Newspaper, ChevronDown, HelpCircle } from "lucide-react";
import { countryCodeToFlag } from "@/lib/country-flag";
import { RegChangeAlertBanner } from "@/components/insight/RegChangeAlertBanner";
import { KnowledgePanelWidget } from "@/components/insight/KnowledgePanel";
import type { KnowledgeSection } from "@/components/insight/KnowledgePanel";

const REG_INTEL_KNOWLEDGE: KnowledgeSection[] = [
  {
    title: "What the Programme Intelligence Profile Does",
    content: "The PIP is auto-generated from your entity register. It captures sector exposure, geographic exposure, and risk profile. Every intelligence item is scored for relevance against your specific PIP before it reaches your feed.",
  },
  {
    title: "Why Not Everything is Relevant",
    content: "A sanctions update affecting Venezuelan crude oil is High relevance for a programme with commodity trading entities and Latin American exposure. It is Not Relevant for a UK-only professional services programme. The PIP makes that distinction automatically.",
  },
  {
    title: "Signal vs Noise",
    content: "The relevance score (High / Moderate / Low / Not Relevant) is generated by the CR Regulatory Intelligence Agent before the analyst sees the item. Not Relevant items are suppressed from the client feed entirely.",
  },
  {
    title: "The CR Analysis Layer",
    content: "Beyond relevance scoring, the agent generates an editorial opinion specific to your programme. This is not a summary of the article — it is the analytical layer your analyst would otherwise write manually.",
  },
  {
    title: "Quick Reference",
    type: "keyvalue",
    pairs: [
      { key: "Legislation", value: "DUAA 2025 Art 6(1)(ea)" },
      { key: "Internal", value: "CR PIP Spec" },
      { key: "Agent", value: "Regulatory Intelligence Agent Spec" },
    ],
  },
];

interface MarketLesson {
  id: string;
  title: string;
  category: string;
  publication_name: string;
  publication_url: string;
  publication_date: string | null;
  summary_text: string | null;
  governance_reflection: string | null;
  jurisdiction_country_code: string | null;
  published: boolean;
  created_at: string;
  relevance_score: string | null;
  relevance_reasoning: string | null;
}

type RelevanceLevel = "high" | "moderate" | "low";

const RELEVANCE_CONFIG: Record<RelevanceLevel, { label: string; className: string }> = {
  high: { label: "HIGH RELEVANCE", className: "bg-destructive/15 text-destructive border-destructive/30" },
  moderate: { label: "MODERATE", className: "bg-amber-100 text-amber-800 border-amber-300 dark:bg-amber-900/30 dark:text-amber-400 dark:border-amber-700" },
  low: { label: "LOW RELEVANCE", className: "text-muted-foreground border-muted-foreground/30 bg-muted/50" },
};

function RelevanceBadge({ score }: { score: string | null }) {
  if (!score || !(score in RELEVANCE_CONFIG)) return null;
  const cfg = RELEVANCE_CONFIG[score as RelevanceLevel];
  return <Badge variant="outline" className={`text-[10px] shrink-0 ${cfg.className}`}>{cfg.label}</Badge>;
}

type FilterOption = "all" | "high" | "all_levels";

export default function RegulatoryBriefingsPage() {
  const { profile } = useAuth();
  const [filter, setFilter] = useState<FilterOption>("all");

  const { data: briefings = [], isLoading } = useQuery({
    queryKey: ["regulatory-briefings", profile?.org_id],
    queryFn: async () => {
      // Fetch published briefings
      const { data, error } = await supabase
        .from("market_lessons" as any)
        .select("*")
        .eq("published", true)
        .order("publication_date", { ascending: false });
      if (error) throw error;
      const all = (data || []) as unknown as MarketLesson[];

      // Fetch suppressions for this org
      if (profile?.org_id) {
        const { data: suppressions } = await supabase
          .from("market_lesson_suppressions" as any)
          .select("market_lesson_id")
          .eq("org_id", profile.org_id);
        const suppressedIds = new Set((suppressions || []).map((s: any) => s.market_lesson_id));
        return all.filter((b) => !suppressedIds.has(b.id));
      }
      return all;
    },
  });

  const filtered = briefings.filter((b) => {
    if (filter === "high") return b.relevance_score === "high";
    return true;
  });

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-display font-semibold text-foreground">
          Regulatory Briefings
        </h1>
        <div className="fvc-gold-rule mt-3 mb-2" />
        <p className="text-sm text-muted-foreground">
          Published regulatory intelligence and governance observations from your CR team.
        </p>
      </div>

      {/* Filter toggles */}
      {briefings.length > 0 && (
        <div className="flex items-center gap-2">
          {(
            [
              { key: "all", label: "All briefings" },
              { key: "high", label: "High relevance" },
              { key: "all_levels", label: "All relevance levels" },
            ] as const
          ).map((opt) => (
            <Button
              key={opt.key}
              variant={filter === opt.key ? "default" : "outline"}
              size="sm"
              className="text-xs h-7"
              onClick={() => setFilter(opt.key)}
            >
              {opt.label}
            </Button>
          ))}
        </div>
      )}

      {isLoading ? (
        <div className="flex items-center justify-center py-16">
          <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
        </div>
      ) : filtered.length === 0 ? (
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-16 text-center">
            <Newspaper className="h-10 w-10 text-muted-foreground/40 mb-4" />
            <p className="text-sm text-muted-foreground max-w-sm">
              {briefings.length > 0
                ? "No briefings match the selected filter."
                : "No regulatory briefings published yet. Your CR team will publish relevant updates here."}
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-4">
          {filtered.map((b) => (
            <Card key={b.id} className="hover:border-primary/20 transition-colors duration-200">
              <CardContent className="p-5">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1 min-w-0 space-y-2">
                    <div className="flex items-center gap-2 flex-wrap">
                      <h3 className="text-sm font-semibold text-foreground leading-snug">
                        {b.title}
                      </h3>
                      {b.jurisdiction_country_code && (
                        <span className="text-sm">{countryCodeToFlag(b.jurisdiction_country_code)}</span>
                      )}
                      <RelevanceBadge score={b.relevance_score} />
                    </div>

                    <div className="flex items-center gap-3 text-[11px] text-muted-foreground">
                      <span>{b.publication_name}</span>
                      <span>·</span>
                      <span>
                        {b.publication_date
                          ? new Date(b.publication_date).toLocaleDateString("en-GB", {
                              day: "numeric",
                              month: "short",
                              year: "numeric",
                            })
                          : "Date unknown"}
                      </span>
                      {b.category && (
                        <>
                          <span>·</span>
                          <Badge variant="outline" className="text-[10px] py-0">
                            {b.category}
                          </Badge>
                        </>
                      )}
                    </div>

                    {b.summary_text && (
                      <p className="text-xs text-muted-foreground leading-relaxed">
                        {b.summary_text}
                      </p>
                    )}

                    {/* Why relevant expandable */}
                    {b.relevance_reasoning && (
                      <Collapsible>
                        <CollapsibleTrigger className="flex items-center gap-1 text-[11px] text-primary hover:underline mt-1">
                          <HelpCircle className="h-3 w-3" />
                          Why relevant to you?
                          <ChevronDown className="h-3 w-3" />
                        </CollapsibleTrigger>
                        <CollapsibleContent>
                          <div className="mt-2 p-2.5 rounded-md bg-muted/50 border border-border space-y-1">
                            {b.relevance_reasoning.split("\n").filter(Boolean).map((line, i) => (
                              <p key={i} className="text-xs text-muted-foreground leading-relaxed">{line}</p>
                            ))}
                          </div>
                        </CollapsibleContent>
                      </Collapsible>
                    )}
                  </div>

                  {b.publication_url && (
                    <a
                      href={b.publication_url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="shrink-0 text-muted-foreground hover:text-foreground transition-colors"
                      title="View source"
                    >
                      <ExternalLink className="h-4 w-4" />
                    </a>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
